language: java
jdk: oraclejdk8
script: mvn package -B
before_deploy: ./scripts/before_deploy.sh
deploy:
  provider: bintray
  file: .bintray.desc
  user: mborges-pivotal
  key:
    secure: afgYEOtRWXJglN7NYq+uAHhKBnIL3nlbm9v5nurf/3ChX1smihWYzEWbhvf1h5A85M2ZhkmJoGbE2KeE76Kju0/gD57LEMBJ6ORWWe1VdY3TfoJOOJ0yhN0FE/1QmtzaNLbZEWg69ZhA5a7Rd0VXDprV2lHobpHKhgwFuPQyiKh91qC90t6vTUXyu6GcubHK+8KtrGVuYPxxPR7HrCwB6x1hRkRC1UlKoH3aiEhYW+GKH2bAgah1DVeL9QnKBfkYyYesmg4Iv1EuUcZI6rYRMZwRhz/tNkBA9RlWSCbgWRmGerqNyI+JfSDSgvvv1tch4AF5gLUSATnUySTmf8r+pqUAbim+qoTuBe4jsOQeCI3K1QtNZSTIR3djCS0lY1mzkmCZEsp4XSs9MiUHtGYVHC/t0sa+RVEqulnN7SzKSs1JVIbG4hsl3+wR/HumEemxgKe36SHjRapbxOQoob3mlkD2Lhv0NuKzAaoh0Gua/9uLVSSkbfTR3jhPGzSqfd1Bj7pBsKaZixsLbjkwelUaGhs0bWBu9Hny+jYBkmCXIPqySHlZkYrIIR7MB/rRuLle5F6wNDIlFSXkI7X5AdWxec+SW7fDadZbwHResE59iJUwMdvPe/ldxHF7V/7Dwp6dCdwuR+tSl5LOiXdKDghxFymZ/55uzjCHTEZofB0qFKw=
  dry-run: false
