#host domain user password [CLSID|ProgId] tagList [async]
opc:
    servers:
    -
        name: matrikon
        host: 192.168.9.188
        domain: CORP
        user: borgem
        password: PASSWORD
        progId: Matrikon.OPC.Simulation.1
    -
        name: graybox
        host: 192.168.9.180
        domain: CORP
        user: borgem
        password: PASSWORD
        progId: Graybox.Simulator.1
    -
        name: osipi
        host: localhost
        domain: INV
        user: mborges
        password: PASSWORD
        progId: OSI.DA.1

## Spring Remote Shell
shell:
    ssh:
        port: 2222
    auth: simple
    auth.simple.user:
        name: admin
        password: admin

## Logging
logging:
    level: 
        org.jinterop: 'ERROR'
        org.jinterop.dcom.*: 'DEBUG'
        org.openscada.opc.lib.da.*: 'DEBUG'
        com.gopivotal.tola.opc.*: 'DEBUG'
        